#!/bin/bash
#
# reportprocess	Recruitment
#
# chkconfig: - 64 36
# description: Recruitment background process
# processname: nohup /usr/bin/java -jar /var/www/html/rekrut/app/commands/recruitment/Recruitment.jar &
check_status() {
	s=`pgrep -f "Recruitment"`
	if [ $s ] ; then
		echo $s
	else
		echo 0
	fi
}

start() {
	pid=$(check_status)

	if [ $pid -ne 0 ] ; then
		echo "Recruitment is already started [PID: $pid]."
		exit 1
	fi

	echo -n "Starting Recruitment: "
	nohup /usr/bin/java -jar /var/www/html/rekrut/app/commands/recruitment/Recruitment.jar > /dev/null 2>&1 &
	echo $! > "/var/www/html/rekrut/app/runtime/Recruitment.pid"
	echo "[OK]"
}

stop() {
	pid=$(check_status)

	if [ $pid -eq 0 ] ; then
		echo "Recruitment is already stopped."
		exit 1
	fi

	echo -n "Stopping Recruitment: "
	kill -9 $pid &
	echo "[OK]"
}

status() {
	pid=$(check_status $1)

	if [ $pid -ne 0 ] ; then
		echo "Recruitment is started [PID: $pid]."
	else
		echo "Recruitment is stopped."
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status
		;;
	restart|reload)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload|status}"
		exit 1
esac

exit 0
